### ISSUE TITLE
JDFTx calculator in ASE interface

### ISSUE THREAD

**Issue by Liuly98** [shankar1729/jdftx#225]
Hi shankar,

Recently, I wanted to use ASE and JDFTx calculator to do NEB calculations, I installed the latest ASE-master version and set all the python path to access the interface file. successfully. but when I started, it gave the following errors:

`    File "/data/software/JDFTx/jdftx-1.7.0/jdftx/scripts/ase/JDFTx.py", line 10, in <module>
  from ase.calculators.interface import Calculator
ModuleNotFoundError: No module named 'ase.calculators.interface'
`
it seemed that in the new version of ASE, there is no "interface" module,  do you have any suggestions for this error if I need to use the new ASE version(because it has a new DyNEB method and it is very attractive to me)?

**Comment by shankar1729** [comment]
Hi Leyu,

Looking quickly at the recent ASE documentation, they seem to have moved the Calculator class. Try changing that import line in the JDFTx ASE script to `from ase.calculators.calculator import Calculator`.

Hopefully that gets you started; it could be that there are other (most likely minor) changes needed within the Calculator class as well. If you get it working, a pull request would be highly appreciated!

Best,
Shankar

**Comment by shankar1729** [comment]
Looking at their source code, they do not appear to be the same. However, I'm not sure why both versions are present; possibly they wanted to move it, while deprecating the old interface.

**Comment by Liuly98** [comment]
Hi Shankar,

I try changing `from ase.calculators.interface import Calculator` in the JDFTx ASE script to  `from ase.calculators.calculator import Calculator` for the latest ASE-master version  as you said, it can run at first, but in some case, it will give the following error:

`Traceback (most recent call last):
  File "test-charged.py", line 247, in <module>
    qn.run(fmax=0.05)
  File "/home/liuly/opt/ase-master/ase/optimize/optimize.py", line 273, in run
    return Dynamics.run(self)
  File "/home/liuly/opt/ase-master/ase/optimize/optimize.py", line 156, in run
    for converged in Dynamics.irun(self):
  File "/home/liuly/opt/ase-master/ase/optimize/optimize.py", line 129, in irun
    self.call_observers()
  File "/home/liuly/opt/ase-master/ase/optimize/optimize.py", line 108, in call_observers
    function(*args, **kwargs)
  File "/home/liuly/opt/ase-master/ase/io/trajectory.py", line 132, in write
    self._write_atoms(image, **kwargs)
  File "/home/liuly/opt/ase-master/ase/io/trajectory.py", line 169, in _write_atoms
    c.write(parameters=calc.todict())
  File "/home/liuly/opt/ase-master/ase/calculators/calculator.py", line 719, in todict
    for key, value in self.parameters.items():
AttributeError: 'JDFTx' object has no attribute 'parameters'`

I think it may have something incompatible between JDFTx ASE script and the latest ASE.

Best,
Leyu
